# Generated by Django 4.2.6 on 2023-11-10 12:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_company_details_year_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='type_of_construction',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Started', 'Started'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('Closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
