# Generated by Django 4.2.6 on 2023-11-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_company_details_type_of_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwsebsandsdvobs',
            name='EEO',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mwsebsandsdvobs',
            name='mwsebs',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mwsebsandsdvobs',
            name='sdvobs',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
    ]
