# Generated by Django 4.2.6 on 2023-11-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_mwsebsandsdvobs_eeo_alter_mwsebsandsdvobs_mwsebs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mwsebsandsdvobs',
            name='MBE',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='payment_bond_percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_phase',
            field=models.CharField(choices=[('Pre-Bid', 'Pre-Bid'), ('Bidding', 'Bidding'), ('Post-Bid', 'Post-Bid'), ('Open-Solicitation', 'Open Solicitation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='bid_bond',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='performance_bond',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
    ]
