# Generated by Django 4.2.6 on 2023-11-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_bid_bid_amount_mwsebsandsdvobs_mbe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_phase',
            field=models.CharField(blank=True, choices=[('Pre-Bid', 'Pre-Bid'), ('Bidding', 'Bidding'), ('Post-Bid', 'Post-Bid'), ('Open-Solicitation', 'Open Solicitation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidding_method',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Selective', 'Selective')], max_length=20),
        ),
    ]
