# Generated by Django 4.2.6 on 2023-11-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_bid_bid_phase_alter_bid_bidding_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='project_completion_time',
            field=models.IntegerField(blank=True),
        ),
    ]
