# Generated by Django 4.2.6 on 2023-11-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_bidhistory_bid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
