# Generated by Django 4.2.6 on 2023-11-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_alter_bidhistory_bid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_phase',
            field=models.CharField(blank=True, choices=[('Pre-Bid', 'Pre-Bid'), ('Bidding', 'Bidding'), ('Post-Bid', 'Post-Bid'), ('Open-Solicitation', 'Open Solicitation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidding_method',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Selective', 'Selective')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='project_completion_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
