# Generated by Django 4.2.6 on 2023-11-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_bid_bid_phase_alter_bid_bidding_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaddendum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
