# Generated by Django 4.2.6 on 2023-11-22 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0019_alter_company_created_at_alter_mwsebsandsdvobs_eeo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcontact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
