# Generated by Django 4.2.6 on 2023-11-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='year_founded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
