# Generated by Django 4.2.6 on 2024-02-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profile_pic',
        ),
    ]
