# Generated by Django 4.2.6 on 2024-03-15 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractors',
            field=models.ManyToManyField(blank=True, related_name='projects_as_contractor', to=settings.AUTH_USER_MODEL),
        ),
    ]
