# Generated by Django 4.2.6 on 2024-03-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_project_contractors'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_specification_files',
            field=models.ManyToManyField(blank=True, related_name='projects', to='apps.projectspecifications'),
        ),
    ]
