# Generated by Django 4.2.6 on 2024-03-18 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_project_project_specification_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_bond',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='liquidated_damages',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='payment_bond_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='bid',
            name='performance_bond',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='bid',
            name='pre_bid_meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='pre_bid_meeting_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='solicitation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
