# Generated by Django 4.2.6 on 2024-03-18 22:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_bid_bid_bond_bid_bid_date_bid_bid_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='csi_division',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('General_Requirements', 'General Requirements'), ('Existing_Conditions', 'Existing Conditions'), ('Concrete', 'Concrete'), ('Masonry', 'Masonry'), ('Metals', 'Metals'), ('Wood_Plastics_and_Composites', 'Wood, Plastics, and Composites'), ('Thermal_and_Moisture_Protection', 'Thermal and Moisture Protection'), ('Openings', 'Openings'), ('Finishes', 'Finishes'), ('Specialties', 'Specialties'), ('Equipment', 'Equipment'), ('Furnishings', 'Furnishings'), ('Special_Construction', 'Special Construction'), ('Conveying_Equipment', 'Conveying Equipment'), ('Plumbing_HVAC', 'Plumbing + HVAC'), ('Electrical_Lighting', 'Electrical + Lighting'), ('Reserved_For_Future_Expansion_1', 'RESERVED FOR FUTURE EXPANSION'), ('Reserved_For_Future_Expansion_2', 'RESERVED FOR FUTURE EXPANSION'), ('Reserved_For_Future_Expansion_3', 'RESERVED FOR FUTURE EXPANSION'), ('Mechanical_Support', 'Mechanical Support'), ('Fire_Suppression', 'Fire Suppression'), ('Plumbing', 'Plumbing'), ('HVAC', 'Heating Ventilating and Air Conditioning'), ('Reserved_For_Future_Expansion_4', 'RESERVED FOR FUTURE EXPANSION'), ('Integrated_Automation', 'Integrated Automation'), ('Electrical', 'Electrical'), ('Communications', 'Communications'), ('Electronic_Safety_and_Security', 'Electronic Safety and Security'), ('Reserved_For_Future_Expansion_5', 'RESERVED FOR FUTURE EXPANSION'), ('Reserved_For_Future_Expansion_6', 'RESERVED FOR FUTURE EXPANSION'), ('Earthwork', 'Earthwork'), ('Exterior_Improvements', 'Exterior Improvements'), ('Utilities', 'Utilities'), ('Transportation', 'Transportation'), ('Waterways_and_Marine_Construction', 'Waterways and Marine Construction'), ('Reserved_For_Future_Expansion_7', 'RESERVED FOR FUTURE EXPANSION'), ('Reserved_For_Future_Expansion_8', 'RESERVED FOR FUTURE EXPANSION'), ('Reserved_For_Future_Expansion_9', 'RESERVED FOR FUTURE EXPANSION'), ('Reserved_For_Future_Expansion_10', 'RESERVED FOR FUTURE EXPANSION'), ('Process_Interconnections', 'Process Interconnections'), ('Material_Processing_and_Handling_Equipment', 'Material Processing and Handling Equipment'), ('Process_Heating_Cooling_and_Drying_Equipment', 'Process Heating, Cooling, and Drying Equipment'), ('Process_Gas_and_Liquid_Handling_Purification_and_Storage_Equipment', 'Process Gas and Liquid Handling, Purification and Storage Equipment'), ('Pollution_Control_Equipment', 'Pollution Control Equipment'), ('Industry-Specific_Manufacturing_Equipment', 'Industry-Specific Manufacturing Equipment'), ('Water_and_Wastewater_Equipment', 'Water and Wastewater Equipment'), ('Reserved_For_Future_Expansion_11', 'RESERVED FOR FUTURE EXPANSION'), ('Electrical_Power_Generation', 'Electrical Power Generation'), ('Reserved_For_Future_Expansion_12', 'RESERVED FOR FUTURE EXPANSION')], default='Developer', max_length=200),
        ),
    ]
