# Generated by Django 4.2.6 on 2024-03-18 23:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_project_csi_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='csi_division',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('General Requirements', 'General Requirements'), ('Existing Conditions', 'Existing Conditions'), ('Concrete', 'Concrete'), ('Masonry', 'Masonry'), ('Metals', 'Metals'), ('Wood Plastics and Composites', 'Wood, Plastics, and Composites'), ('Thermal and Moisture Protection', 'Thermal and Moisture Protection'), ('Openings', 'Openings'), ('Finishes', 'Finishes'), ('Specialties', 'Specialties'), ('Equipment', 'Equipment'), ('Furnishings', 'Furnishings'), ('Special Construction', 'Special Construction'), ('Conveying Equipment', 'Conveying Equipment'), ('Plumbing HVAC', 'Plumbing + HVAC'), ('Electrical Lighting', 'Electrical + Lighting'), ('Reserved For Future Expansion 1', 'RESERVED FOR FUTURE EXPANSION'), ('Reserved For Future Expansion 2', 'RESERVED FOR FUTURE EXPANSION'), ('Reserved For Future Expansion 3', 'RESERVED FOR FUTURE EXPANSION'), ('Mechanical Support', 'Mechanical Support'), ('Fire Suppression', 'Fire Suppression'), ('Plumbing', 'Plumbing'), ('HVAC', 'Heating Ventilating and Air Conditioning'), ('Reserved For Future Expansion 4', 'RESERVED FOR FUTURE EXPANSION'), ('Integrated Automation', 'Integrated Automation'), ('Electrical', 'Electrical'), ('Communications', 'Communications'), ('Electronic Safety and Security', 'Electronic Safety and Security'), ('Reserved For Future Expansion 5', 'RESERVED FOR FUTURE EXPANSION'), ('Reserved For Future Expansion 6', 'RESERVED FOR FUTURE EXPANSION'), ('Earthwork', 'Earthwork'), ('Exterior Improvements', 'Exterior Improvements'), ('Utilities', 'Utilities'), ('Transportation', 'Transportation'), ('Waterways and Marine Construction', 'Waterways and Marine Construction'), ('Reserved For Future Expansion 7', 'RESERVED FOR FUTURE EXPANSION'), ('Reserved For Future Expansion 8', 'RESERVED FOR FUTURE EXPANSION'), ('Reserved For Future Expansion 9', 'RESERVED FOR FUTURE EXPANSION'), ('Reserved For Future Expansion 10', 'RESERVED FOR FUTURE EXPANSION'), ('Process Interconnections', 'Process Interconnections'), ('Material Processing and Handling Equipment', 'Material Processing and Handling Equipment'), ('Process Heating Cooling and Drying Equipment', 'Process Heating, Cooling, and Drying Equipment'), ('Process Gas and Liquid Handling Purification and Storage Equipment', 'Process Gas and Liquid Handling, Purification and Storage Equipment'), ('Pollution Control Equipment', 'Pollution Control Equipment'), ('Industry-Specific Manufacturing Equipment', 'Industry-Specific Manufacturing Equipment'), ('Water and Wastewater Equipment', 'Water and Wastewater Equipment'), ('Reserved For Future Expansion 11', 'RESERVED FOR FUTURE EXPANSION'), ('Electrical Power Generation', 'Electrical Power Generation'), ('Reserved For Future Expansion 12', 'RESERVED FOR FUTURE EXPANSION')], default='Developer', max_length=200),
        ),
    ]
