# Generated by Django 4.2.6 on 2024-04-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_project_project_takeoff_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_Takeoff_files',
            field=models.ManyToManyField(blank=True, related_name='projectTakeoff', to='apps.project_takeoff_documents'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_plans_files',
            field=models.ManyToManyField(blank=True, related_name='projectPlans', to='apps.projectplans'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_specification_files',
            field=models.ManyToManyField(blank=True, related_name='specificationFiles', to='apps.projectspecifications'),
        ),
    ]
