# Generated by Django 4.2.6 on 2023-11-13 11:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_company_details_type_of_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='type_of_construction',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial')], max_length=200),
        ),
    ]
