# Generated by Django 4.2.6 on 2024-04-03 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_project_project_takeoff_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='city',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='state',
            new_name='address',
        ),
        migrations.CreateModel(
            name='SubAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.authority')),
            ],
        ),
    ]
