# Generated by Django 4.2.6 on 2024-04-03 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_authority_rename_city_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='authority',
            field=models.ForeignKey(choices=[], default=None, on_delete=django.db.models.deletion.CASCADE, to='apps.authority'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='subauthority',
            field=models.ForeignKey(blank=True, choices=[], null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.subauthority'),
        ),
    ]
