# Generated by Django 4.2.6 on 2024-04-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_project_authority_project_subauthority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subauthority',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
