# Generated by Django 4.2.6 on 2024-04-03 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_authority_id_alter_subauthority_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='authority',
            field=models.ForeignKey(blank=True, choices=[], null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.authority'),
        ),
    ]
