# Generated by Django 4.2.6 on 2023-11-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_bid_project_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidhistory',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bidhistory',
            name='bid_outcome',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='mwsebsandsdvobs',
            name='EEO',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mwsebsandsdvobs',
            name='MBE',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mwsebsandsdvobs',
            name='mwsebs',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mwsebsandsdvobs',
            name='sdvobs',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='bid_bond',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='bid_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='bid_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='liquidated_damages',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='payment_bond_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='performance_bond',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='pre_bid_meeting_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='pre_bid_meeting_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='solicitation_date',
            field=models.DateField(blank=True),
        ),
    ]
