# Generated by Django 4.2.6 on 2023-11-15 19:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_project_city_alter_project_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidhistory',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bidhistory',
            name='bid_outcome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bidhistory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.company'),
        ),
        migrations.AlterField(
            model_name='bidhistory',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.project'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='bid_bond',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='bid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='bid_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='liquidated_damages',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='payment_bond_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='performance_bond',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='pre_bid_meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='pre_bid_meeting_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.project'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='solicitation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
