# Generated by Django 4.2.6 on 2024-04-03 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_rename_id_authority_authority_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.authority'),
        ),
    ]
