# Generated by Django 4.2.6 on 2023-11-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mwsebsandsdvobs',
            name='EEO',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mwsebsandsdvobs',
            name='MBE',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mwsebsandsdvobs',
            name='mwsebs',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mwsebsandsdvobs',
            name='sdvobs',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5, null=True),
        ),
    ]
